#!/usr/bin/env python3

from jinja2 import Template
import glob,os,time

app = 'App'

tm = Template(
'''
<!-- Script autogenerated by Svelte-Jinja (author: Dan Ellis) -->

<script>
	{{globals}}
</script>

<main>
	{{body}}
</main>

<style>
	{{stylesheet}}
</style>

''')


watch = glob.glob(__file__.replace('gen_template.py','')+app+'.*')

updated = 0


while True:
    new = max([int(os.popen('date -r %s +%s'%(x,'%s')).read()) for x in watch])

    if new != updated:
        print('Updating',app,new)
        code = tm.render(globals=open(app+'.js','r').read(), body = open(app+'.html','r').read(),stylesheet=open(app+'.css','r').read())
        # print(app,code)
        with open('../%s.svelte'%app,'w') as f:
            f.write(code)

        updated = new

    else:
        time.sleep(4)
