#!/usr/bin/env python3

from jinja2 import Template
import glob

app = 'App'

tm = Template(
'''
<--! Script autogenerated by Svelte-Jinja (author: Dan Ellis) -->

<script>
	{{globals}}
</script>

<main>
	{{body}}
</main>

<style>
	{{stylesheet}}
</style>

''')


code = tm.render(globals=open(app+'.js','r').read(), body = open(app+'.html','r').read(),stylesheet=open(app+'.css','r').read())

print(app,code)

with open('../%s.svelte'%app,'w') as f:
    f.write(code)
